### PR TITLE
refactor vagrantfile

### PR DESCRIPTION
**Pull request by elseym**
refactored the vagrantfile:
- removed ancient virtualbox guest additions fixer
- re-arranged most of the statements in logical order
- put all config-loading stuff into own function
- added comments
- de-duplicated code as much as possible
- all obligatory config keys now have sensible defaults
- more minor fixes

[Review on Reviewable](https://reviewable.io/reviews/mayflower/wasted/74)

### CODE REVIEW

**Comment by mmoll** [comment]
@elseym what's the status here?

**Comment by elseym** [comment]
probably needs some reviewing. anyone care to test it? anyone care to comment on the approach? prettyplease? 🐱

**Comment by fpletz** [comment]
Mergen wenns baut.

**Comment by mmoll** [comment]
seems to work fine here, merged, thanks @elseym!

**Pull request merged**
